services:
    share.admin.item:
        class: ShareBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.share", label: "group.item_editor" }
        arguments:
            - ~
            - ShareBundle\Entity\Item
            - ~
        calls:
            - [ setTranslationDomain, [ShareBundle] ]

    share.admin.category:
        class: ShareBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.share", label: "group.category_editor" }
        arguments:
            - ~
            - ShareBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [ShareBundle] ]

    share.admin.rtf_block:
        class: ShareBundle\Admin\RTFBlockAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.rtf_block", label: "group.rtf_block"}
        arguments:
            - ~
            - ShareBundle\Entity\RTFBlock
            - ~
        calls:
            - [ setTranslationDomain, [ShareBundle] ]