services:
    share.admin.item:
        class: ShareBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.share", label: "group.item_editor" }
        arguments:
            - ~
            - ShareBundle\Entity\Item
            - ~
        calls:
            - [ setTranslationDomain, [ShareBundle] ]

    share.admin.item_category:
        class: ShareBundle\Admin\ItemCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.share", label: "group.item_category_editor" }
        arguments:
            - ~
            - ShareBundle\Entity\ItemCategory
            - ~
        calls:
            - [ setTranslationDomain, [ShareBundle] ]