services:
    help.block.help_list:
        class: HelpCenterBundle\Block\ListHelpArticleBlockService
        arguments:
          - help.block.help_list
          - '@templating'
          - '@?doctrine'
        tags:
          - { name: sonata.block }