# help center========================================================
help_center:
    path: /helpcenter
    defaults:
        _controller: HelpCenterBundle:HelpCenter:list

help_center_view:
    path: /helpcenter/{id}-{slug}
    defaults:
        _controller: HelpCenterBundle:HelpCenter:view
    requirements:
        id: "\\d+"
        slug: "([a-zA-Z\\-0-9\\_]+)?"