services:
    game.admin.game:
        class: GameBundle\Admin\GameAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.game", label: "group.game_editor" }
        arguments:
          - ~
          - GameBundle\Entity\Game
          - ~
        calls:
          - [ setTranslationDomain, [GameBundle] ]

    game.admin.server:
        class: GameBundle\Admin\ServerAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.game", label: "group.server_editor" }
        arguments:
          - ~
          - GameBundle\Entity\Server
          - ~
        calls:
          - [ setTranslationDomain, [GameBundle] ]

    game.admin.game_genre:
        class: GameBundle\Admin\GameGenreAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.game", label: "group.game_genre_editor" }
        arguments:
          - ~
          - GameBundle\Entity\GameGenre
          - ~
        calls:
          - [ setTranslationDomain, [GameBundle] ]

    game.admin.server_has_item:
        class: GameBundle\Admin\ServerHasItemAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: 'group.game', label: "group.server_has_item_editor", show_in_dashboard: false }
        arguments:
          - ~
          - GameBundle\Entity\ServerHasItem
          - ~
        calls:
          - [ setTranslationDomain, [GameBundle] ]