services:
    game.block.item_list:
        class: GameBundle\Block\ListItemsBlockService
        arguments:
          - game.block.item_list
          - '@templating'
          - '@?doctrine'
        tags:
          - { name: sonata.block }