view_list:
  path: /games
  defaults:
    _controller: GameBundle:Game:list

game_how_sell_to_us:
  path: /game/{slug}/sell-to-us
  defaults:
    _controller: GameBundle:Game:sellToUs
  requirements:
    slug: "([a-zA-Z\\-0-9\\_]+)?"

game_how_it_work:
  path: /game/{slug}/how-it-work
  defaults:
    _controller: GameBundle:Game:howItWork
  requirements:
    slug: "([a-zA-Z\\-0-9\\_]+)?"

game_how_it_work_view:
  path: /game/{slug}/how-it-work/{id}-{helpSlug}
  defaults:
    _controller: GameBundle:Game:howItWork
  requirements:
    slug: "([a-zA-Z\\-0-9\\_]+)?"
    id: "\\d+"
    helpSlug: "([a-zA-Z\\-0-9\\_]+)?"

view_game_server:
  path: /game/{slug}/{server}
  defaults:
    _controller: GameBundle:Game:viewServer
  requirements:
    slug: "([a-zA-Z\\-0-9\\_]+)?"
    server: "([a-zA-Z\\-0-9\\_]+)?"

view_game_server_category:
  path: /game/{slug}/{server}/{category}
  defaults:
    _controller: GameBundle:Game:viewServerCategory
  requirements:
    slug: "([a-zA-Z\\-0-9\\_]+)?"
    server: "([a-zA-Z\\-0-9\\_]+)?"
    category: "([a-zA-Z\\-0-9\\_]+)?"

view_game:
  path: /game/{slug}{category}
  defaults:
    _controller: GameBundle:Game:view
    category: null
  requirements:
    slug: "((?!_\\[a-zA-Z\\-0-9]+)([a-zA-Z\\-0-9]+\\/?))+"
    category: "([a-zA-Z\\-0-9\\_]+)?"