sonata_admin:
    title: book library
    title_logo: /bundles/admin/images/admin_logo.png
    show_mosaic_button: false
    security:
        handler: sonata.admin.security.handler.acl
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        admin_permissions: [CREATE, LIST, EDIT, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    templates:
        short_object_description: 'MediaBundle:Helper:short-object-description.html.twig'
    options:
        title_mode: single_image

    assets:
        extra_javascripts:
            - bundles/sonatapage/sonata-page.back.min.js
            - bundles/admin/js/textcounter.min.js
            - bundles/admin/js/codemirror/codemirror.js
            - bundles/admin/js/codemirror/autorefresh.js
            - bundles/admin/js/codemirror/css.js
            - bundles/admin/js/codemirror/xml.js
            - bundles/admin/js/codemirror/javascript.js
            - bundles/admin/js/codemirror/htmlmixed.js
        extra_stylesheets:
            - bundles/sonatapage/sonata-page.back.min.css
            - bundles/admin/css/codemirror/codemirror.css


    dashboard:
        groups:
            group.game:
                label: group.game
                label_catalogue: GameBundle
                icon: <i class="fa fa-gamepad"></i>
            group.media:
                label: group.media
                label_catalogue: MediaBundle
                icon: <i class="fa fa-files-o"></i>
            group.slider:
                label: group.slider
                label_catalogue: SliderBundle
                icon: <i class="fa fa-picture-o"></i>
            group.share:
                label: group.share
                label_catalogue: ShareBundle
                icon: <i class="fa fa-text-width"></i>
                items:
                    - share.admin.item_category
                    - share.admin.item
            group.help_center:
                label: group.help_center
                label_catalogue: HelpCenterBundle
                icon: <i class="fa fa-question-circle"></i>
                items:
                    - help_center.admin.category
                    - help_center.admin.article
            group.rtf_block:
                label: group.rtf_block
                label_catalogue: ShareBundle
                icon: <i class="fa fa-text-width"></i>
            group.menu:
                label: group.menu
                label_catalogue: MenuBundle
                icon: <i class="fa fa-tasks"></i>
            group.order:
                label: group.order
                label_catalogue: OrderBundle
                icon: <i class="fa fa-bell-o"></i>
            sonata_page:
                label: ~
                label_catalogue: SonataPageBundle
                icon: <i class="fa fa-sitemap"></i>
                items:
                    - sonata.page.admin.page
                    - sonata.page.admin.page_redirect
                    - sonata.page.admin.site
                    - sonata.page.admin.site_variables
                    - sonata.page.admin.site_variables_placement

        blocks:
             - { position: center, type: sonata.admin.block.admin_list }