services:
    sonata.admin.media_image:
        class: MediaBundle\Admin\MediaImageAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: "group.media", label: "group.media_image_editor" }
        arguments:
        - ~
        - MediaBundle\Entity\MediaImage
        - ~
        calls:
        - [ setTranslationDomain, [MediaBundle] ]