services:
    product.admin.product:
        class: ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.product", label: "group.product_editor" }
        arguments:
            - ~
            - ProductBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [ProductBundle] ]