services:
    product.block.main_game:
        class: ProductBundle\Block\GameProductInMainBlockService
        arguments:
          - product.block.main_game
          - '@templating'
          - '@app.entity_manager'
        tags:
          - { name: sonata.block }

    product.block.in_main:
      class: ProductBundle\Block\ProductInMainBlockService
      arguments:
        - product.block.in_main
        - '@templating'
        - '@request_stack'
        - '@app.entity_manager'
      tags:
        - { name: sonata.block }