# products ========================================================
product_view:
    path: /i_{id}_{slug}
    defaults:
        _controller: ProductBundle:Product:view
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"
        id: "\\d+"