# products ========================================================
product_view:
    path: /p_{slug}
    defaults:
        _controller: ProductBundle:Product:view
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"