knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image:
            local:
                directory: "%media_base_path%"
                create: true

    filesystems:
        image:
            adapter: image