# Main page ============================================
index:
  path: /
  defaults:
    _controller: AppBundle:Default:index

items:
  path: /items
  defaults:
    _controller: AppBundle:Default:items

sell_to_us:
  path: /sell-to-us
  defaults:
    _controller: AppBundle:Default:sellToUs


block__ajax:
  path: /_block/ajax/{blockType}/{blockId}
  defaults:
    _controller: AppBundle:Block:ajax
  methods: [GET, POST]
  requirements:
    blockType: .+
    blockId: .+