# Main page ============================================
index:
  path: /
  defaults:
    _controller: AppBundle:Default:index

search:
  path: /search
  defaults:
    _controller: AppBundle:Default:search


block__ajax:
  path: /_block/ajax/{blockType}/{blockId}
  defaults:
    _controller: AppBundle:Block:ajax
  methods: [GET, POST]
  requirements:
    blockType: .+
    blockId: .+