services:
  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

#  app.twig.extension:
#    class: "AppBundle\\Twig\\AppExtension"
#    arguments:
#      - '@translator'
#      - '@router'
#    tags:
#      - { name: twig.extension }

#  app.twig.extension.sort:
#      class: "AppBundle\\Twig\\SortByFieldExtension"
#      tags:
#        - { name: twig.extension }

  app.twig.extension.genre:
      class: GameBundle\Twig\GameExtension
      arguments:
        - '@game.router.helper'
      tags:
        - { name: twig.extension }