services:
    server.admin.server:
        class: ServerBundle\Admin\ServerAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.server", label: "group.server_editor" }
        arguments:
          - ~
          - ServerBundle\Entity\Server
          - ~
        calls:
          - [ setTranslationDomain, [ServerBundle] ]

    server.admin.server_has_item:
        class: ServerBundle\Admin\ServerHasItemAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: 'group.server', label: "group.server_has_item_editor", show_in_dashboard: false }
        arguments:
        - ~
        - ServerBundle\Entity\ServerHasItem
        - ~
        calls:
        - [ setTranslationDomain, [ServerBundle] ]