services:
    comment.block.list_comments:
        class: "CommentBundle\\Block\\ListCommentBlockService"
        arguments:
          - comment.block.list_comments
          - '@templating'
          - '@app.entity_manager'
        tags:
          - { name: sonata.block }
