services:
  discount.block.pack:
      class: DiscountBundle\Block\DiscountBlockService
      arguments:
        - discount.block.pack
        - '@templating'
        - '@app.entity_manager'
      tags:
        - { name: sonata.block }